# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: j0113
# "service" is the name of this project. This will also be added to your AWS resource names.
service: quiztopia-serverless-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - arn:aws:dynamodb:eu-north-1:*:table/Quiztopia-Quiz
        - arn:aws:dynamodb:eu-north-1:*:table/Quiztopia-Users
        - arn:aws:dynamodb:eu-north-1:*:table/Quiztopia-Leaderboard

functions:
  addQuestionToQuiz:
    handler: functions/addQuestionToQuiz/index.handler
    events:
      - httpApi:
          path: /quiz/question
          method: post

  createAccount:
    handler: functions/createAccount/index.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post

  createQuiz:
    handler: functions/createQuiz/index.handler
    events:
      - httpApi:
          path: /quiz
          method: post

  deleteQuiz:
    handler: functions/deleteQuiz/index.handler
    events:
      - httpApi:
          path: /quiz/{quizId}
          method: delete

  getAllQuiz:
    handler: functions/getAllQuiz/index.handler
    events:
      - httpApi:
        path: /quiz
        method: get

  getQuizById:
    handler: functions/getQuizById/index.handler
    events:
      - httpApi:
        path: /quiz/{userId}/{quizId}
        method: get

  loginAccount:
    handler: functions/loginAccount/index.handler
    events:
      - httpApi:
        path: /auth/login
        method: get
